sudo: false

language: elixir
elixir: 1.6.1
otp_release: 20.2

notifications:
  email: false

env:
  MIX_ENV=test

script:
  - mix compile --all-warnings --warnings-as-errors
  - mix format --check-formatted
  - mix credo --strict
  - mix test
